### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by haesleinhuepf** [jacobtomlinson/gpu-python-tutorial#7]
Hi @jacobtomlinson ,

this is an amazing resource! Thanks for sharing openly! I was just wondering under which conditions one could reuse the tools and code provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by jacobtomlinson** [comment]
This tutorial has now moved to the [NVIDIA Accelerated Computing Hub](https://github.com/NVIDIA/accelerated-computing-hub/tree/main/gpu-python-tutorial) and is now available under a [creative commons license](https://github.com/NVIDIA/accelerated-computing-hub/blob/main/LICENSE).
