### ISSUE TITLE
add instruction to turn off google colab autocomplete

### ISSUE THREAD

**Issue by raybellwaves** [jacobtomlinson/gpu-python-tutorial#8]
Google colab has autocomplete by default (https://blog.google/technology/developers/google-colab-ai-coding-features/ - there may be better links).

When I got up to the lab section, google colab suggested code to me which obviously defeats the purpose of a lab.

May be worth adding instructions at the top of the lab notebooks for how to turn of autocomplete by default

**Comment by jacobtomlinson** [comment]
That's hilarious. I didn't know that was a thing. We should definitely suggest turning that off.

**Comment by raybellwaves** [comment]
![Screenshot 2024-06-17 at 1 17 38 PM](https://github.com/jacobtomlinson/gpu-python-tutorial/assets/17162724/ea485e2e-5fb9-444a-8663-e9c87a67ec62)

**Comment by raybellwaves** [comment]
![Screenshot 2024-06-17 at 1 19 31 PM](https://github.com/jacobtomlinson/gpu-python-tutorial/assets/17162724/08962562-82a2-4811-9d8b-de08c34e745d)
